### ISSUE TITLE
Fails install for Kali 2019.4 VHD in Hyper-V using ./install --kali

### ISSUE THREAD

**Issue by jacobhargrave** [mitre/caldera#1660] opened 2020-05-16 20:23 UTC
[install_log.txt](https://github.com/mitre/caldera/files/4639166/install_log.txt)

**Comment by privateducky** [comment] 2020-05-18 11:11
the install.sh script is not working on all operating systems right now (several side-cases stopping it from doing so). we'll be working on making this more robust-- but in the meantime, you should just follow the "normal" install instructions on GitHub:

1. Clone repo
2. Pip install requirements

**Comment by privateducky** [comment] 2020-05-18 11:12
duplicate of: https://github.com/mitre/caldera/issues/1654

**Closed by privateducky** 2020-05-18 11:12 UTC
