### ISSUE TITLE
v2.8 Saving Global Timer settings doesn't write to conf/agents.yml

### ISSUE THREAD

**Issue by clr2of8** [mitre/caldera#1857] opened 2020-09-05 16:58 UTC
Setting timers under "Global Timers" for agents doesn't update the conf/agent.yml file timer settings or settings for existing agents. Is it supposed to?

Also, what effect does the untrusted timer have? If an agent doesn't checkin within (untrusted-timer + max-sleep) it gets marked as untrusted and then what? No operations can be performed on the agent? Any other affects?

Thank you for your help in helping me understand the intent here.
-Carrie

**Comment by wbooth** [comment] 2020-09-08 13:27
Hi Carrie, I've added a ticket to investigate the global timers not saving. As to the untrusted timer, the behavior you describe is correct. When the agent has not checked in for the defined period of time it is no longer tasked with actions to perform.

**Comment by wbooth** [comment] 2020-10-07 17:22
Hi @clr2of8 , the file write to conf/agents.yml only occurs as shutdown and I confirmed that it updating with the numbers from the gui. I'm going to close this issue as it is intended behavior and will make a note about the global timers -- that section of the agent modal could be improved. first it could show the existing config values, second it should have the option to update existing agents. thanks for bring this up.

**Closed by wbooth** 2020-10-07 17:22 UTC
Labels: bug
