### ISSUE TITLE
Fails install using sudo ./install.sh --ubuntu

### ISSUE THREAD

**Issue by devsecops101** [mitre/caldera#1654] opened 2020-05-14 19:12 UTC
[+] Python virtualenv installed
[+] Caldera python venv installed
ERROR: Could not find a version that satisfies the requirement aiohttp-jinja2==1.2.0 (from -r /home/caldera/caldera/requirements.txt (line 1)) (from versions: 0.0.1, 0.0.2, 0.1.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.1, 0.6.2, 0.7.0, 0.8.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0)
ERROR: No matching distribution found for aiohttp-jinja2==1.2.0 (from -r /home/caldera/caldera/requirements.txt (line 1))
[x] Caldera python requirements FAILED to install
1
[-] Building documentation
-su: /home/caldera/caldera/calderaenv/bin/sphinx-build: No such file or directory
[x] sphinx documentation FAILED to install
[x] Caldera installer FAILED to install critical components
[x] See install_log.txt for details

**Comment by jacobhargrave** [comment] 2020-05-16 17:15
Hello, I am having a similar issue. I have tried the following:
sudo ./install.sh --ubuntu
the above command as root instead of using sudo
running pip install -r requirements.txt first (which fails and must be run as pip3 to work)
and running ./install.sh without the --ubuntu flag
All attempts result in the following output:

root@Ubuntu-Caldera:/home/student/Desktop/caldera# ./install.sh --ubuntu
[-] Installing on Ubuntu (Debian)...
[-] Checking for GO
[-] Installing GO
Reading package lists... Done
Building dependency tree       
Reading state information... Done
software-properties-common is already the newest version (0.98.9).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://mx.archive.ubuntu.com/ubuntu focal InRelease                                
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Ign:4 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal InRelease
Get:5 http://mx.archive.ubuntu.com/ubuntu focal-updates InRelease [107 kB]
Err:6 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal Release           
  404  Not Found [IP: 91.189.95.83 80]
Get:7 http://mx.archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]            
Reading package lists... Done        
E: The repository 'http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
[x] GO FAILED to install
[-] Checking for MinGW
/usr/bin/x86_64-w64-mingw32-gcc
[+] MinGW already installed
[-] Checking for Python
/usr/bin/python3
[+] Python already installed
[-] Checking for Pip
/usr/bin/pip3
[+] Pip already installed
[-] Generating Random Values
[+] caldera random api_keys installed
[+] caldera random crypt_salt installed
[+] Random Values added to default.yml
[-] Installing on GO dependencies
./install.sh: line 67: go: command not found
[x] GO github FAILED to install
./install.sh: line 69: go: command not found
[x] GO oath2 FAILED to install
[-] Setting up Python venv
[+] Python virtualenv installed
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--app-data APP_DATA] [--clear-app-data] [--discovery {builtin}] [-p py] [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed]
                  [--activators comma_sep_list] [--clear] [--system-site-packages] [--symlinks | --copies] [--no-download | --download] [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip]
                  [--no-setuptools] [--no-wheel] [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: argument dest: the destination . is not write-able at /home/student/Desktop/caldera
[x] Caldera python venv FAILED to install
1
-bash: /home/student/Desktop/caldera/calderaenv/bin/pip: No such file or directory
[x] Caldera python requirements FAILED to install
1
[-] Building documentation
-bash: /home/student/Desktop/caldera/calderaenv/bin/sphinx-build: No such file or directory
[x] sphinx documentation FAILED to install
[x] Caldera installer FAILED to install critical components
[x] See install_log.txt for details
root@Ubuntu-Caldera:/home/student/Desktop/caldera# 
[install_log.txt](https://github.com/mitre/caldera/files/4638809/install_log.txt)

**Comment by privateducky** [comment] 2020-05-18 11:13
duplicate of: https://github.com/mitre/caldera/issues/1615

we are working on resolving, however you can follow the install instructions on GitHub and avoid the install.sh script entirely in the meantime.

**Closed by privateducky** 2020-05-18 11:13 UTC
Labels: Needs investigation
