### ISSUE TITLE
Agent Beaconing over HTTPS

### ISSUE THREAD

**Issue by cyber-yinzer** [mitre/caldera#1953] opened 2020-11-24 07:04 UTC
**Describe the bug**
When someone enables the SSL plug on the server, it will allow for administrative access and initial deployment of an agent. It contacts once but then does not beacon home again. All of the plugins reference 8888. Should they switch to 8443 upon enabling SSL?

**To Reproduce**
Enable SSL, set your SSL Cert to a digitally sign one (LetsEncrypt), and test over 8443. I've tried over Azure and isolated subnet. Set up your agents normally then disable listening on 8888 of the caldera to ensure nothing funnels to the service.

**Expected behavior**
If the services are to run over HTTPS (8443), plugins should update from 8888 to 8443

**Screenshots**

![image](https://user-images.githubusercontent.com/56932578/100059463-1f4a4600-2df9-11eb-99e3-f4bab3d3b2d8.png)

![image](https://user-images.githubusercontent.com/56932578/100059527-3ab55100-2df9-11eb-96ee-46f998d890fd.png)

**Desktop (please complete the following information):**
Linux, Windows

**Additional context**
If the services are to remain over 8888 with 8443 allowing the initial contact + administrative pane, then so be it. But nothing truly indicates in the documentation the expected behavior.

**Comment by cyber-yinzer** [comment] 2020-11-24 21:41
As a note...

I went back onto my local host and enable 8888 ports again. The beaconing did NOT return.

**Comment by cyber-yinzer** [comment] 2020-12-01 16:50
Any update on this? Assuming holidays are a factor but want to keep moving with this project for testing.

**Comment by unkempthenry** [comment] 2020-12-01 17:06
Hi @cyber-yinzer , 

Not 100% sure what you mean by "plugins should update from 8888 to 8443". 

Agents won't automatically be able to switch from http to https after they've been started.  You'll want to set up ssl before deploying the agents.  The listening address can be changed when copying and pasting the command to deploy the agents. (replace "http://<caldera server>:8888" with "http://<caldera server>:8443" in the command line)

**Comment by cyber-yinzer** [comment] 2020-12-01 17:12
> Hi @cyber-yinzer ,
> 
> Not 100% sure what you mean by "plugins should update from 8888 to 8443".
> 
> Agents won't automatically be able to switch from http to https after they've been started. You'll want to set up ssl before deploying the agents. The listening address can be changed when copying and pasting the command to deploy the agents. (replace `http://<caldera server>:8888` with `http://<caldera server>:8443` in the command line)

In order of steps:

1. Setup caldera
2. Setup SSL Cert
3. Install SSL Cert on Caldera
4. Reboot
5. Deploy agent

The agent will initially check in and confirm connection but it does not continue to beacon or take commands with 8443.

**Comment by domainicus** [comment] 2020-12-21 21:07
Hi @cyber-yinzer,

Just tested the SSL plugin. I'll update the documentation, but the only issue I see is that the last line in the `plugins/ssl/conf/haproxy.conf` file may need to be updated if you've changed the `host` or `port` values in CALDERA's `conf/local.yml`.

The line:
```
server caldera_main 127.0.0.1:8888 cookie caldera_main
```

Should match the host / port in your CALDERA conf file. For example, if CALDERA host/port is set to `192.168.0.100`/`8000`:
```
server caldera_main 192.168.0.100:8000 cookie caldera_main
```

The need for this change will be apparent if you get an HTTP 503 error when trying to access the UI over SSL.

After manually changing the 8888 port to 8443 in the agent command, I also had to disable PowerShell's SSL certificate checks:

```
[System.Net.ServicePointManager]::ServerCertificateValidationCallback={$true};
```

If these don't solve your issue, happy to help. I'd be curious to know what you're doing when you're "[disabling] listening on 8888 of the caldera".

**Comment by cyber-yinzer** [comment] 2020-12-22 17:58
Hey @domainicus,

Thanks for the response first and foremost. 

As a note, I am not intentionally disabling 8888 during the initial setup. I was trying to rule out the service from being offered at 8888 for admin authentication. I only want access over 8443. I just closed the UFW rule for 8888 to force that.

I have a LetsEncrypt cert offered to avoid the powershell issue.

Looking at `caldera/conf/`there is no `local.yml`. I see agents, default, payloads, and the master.yml file I copied to run caldera off of instead of the default. Config below:

```
ability_refresh: 60
api_key_blue: BLUEADMIN123
api_key_red: ADMIN123
app.contact.gist: API_KEY
app.contact.html: /weather
app.contact.http: http://0.0.0.0:8888
app.contact.tcp: 0.0.0.0:7010
app.contact.udp: 0.0.0.0:7011
app.contact.websocket: 0.0.0.0:7012
crypt_salt: REPLACE_WITH_RANDOM_VALUE
encryption_key: ADMIN123
exfil_dir: /tmp
host: 0.0.0.0
```

Looking at `plugins/ssl/conf/haproxy.conf`and it does not exist either. The pathing is `plugins/ssl/templates/haproxy.conf` and the config below:

```
global
 maxconn 20000
nbproc 1
nbthread 4
ssl-default-bind-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY130$
ssl-default-bind-options ssl-min-ver TLSv1.1 no-tls-tickets

defaults
    timeout connect 10s
    timeout client 30s
    timeout server 30s
    mode http
    option forwardfor
    option http-server-close

frontend caldera-https
    bind *:8443 ssl crt plugins/ssl/conf/fullchain.pem
    http-request add-header proxy_port 8443
    http-request set-header X-Forwarded-Proto https
    default_backend caldera_server

backend caldera_server
    balance leastconn
    cookie SERVERUSED insert indirect nocache
    default-server maxconn 20
    server caldera_main 127.0.0.1:8888 cookie caldera_main
```

Since my initial build, I have nuked it and started from scratch. (v2.9) Now the SSL plugin won't stay and keeps reverting back to 8888.

What am I missing? I wrote out my steps in my wiki if you want to see specifically what I am doing. Ping me when you can.

Thanks!

**Comment by domainicus** [comment] 2020-12-24 16:18
I can confirm that setting the host value to 0.0.0.0 and leaving the 127.0.0.1 in the haproxy config will work. You could also try setting the host to 127.0.0.1 to avoid needing a UFW rule.

I'm not sure I understand what you mean by "the SSL plugin won't stay and keeps reverting back to 8888". Can you access the UI at https://[YOUR_IP]:8443 and then it stops working? Are you making sure to redeploy agents and change the server variable to the HTTPS service when deploying sandcat agents?

**Comment by cyber-yinzer** [comment] 2020-12-24 16:26
Hey @domainicus 

I can't get to 8443 at all.

I've installed haproxy, rebooted, and access caldera at 8888. I enabled the SSL plugin, set my address to https://[myIP]:8443. Stop/start the service. And it goes back to 8888. I've even tried rebooting the full box after applying the settings with no luck.

I've even examined the .yml file after I set the 8443 settings and it did not get modified. 

***NOTE I AM NOT PROMOTING MY SITE NOR DO I HAVE ANY MODELS SETUP TO MAKE AD REVENUE***

https://wiki.kopacko.us/doku.php?id=resources:security:red:caldera

Here are my exact steps. I'd love to know what I am missing.

**Comment by domainicus** [comment] 2020-12-24 16:30
Is haproxy listening? `ss -plnt | grep 8443`

The config files need to be modified while CALDERA is shut down to avoid the server overwriting changes.

**Comment by cyber-yinzer** [comment] 2020-12-24 16:31
Does it make sense to manually set 8443 in the yml file instead of using the GUI?

**Comment by domainicus** [comment] 2020-12-24 16:34
It shouldn't be necessary. And if you set that as the port it will prevent haproxy from listening on 8443.

**Comment by cyber-yinzer** [comment] 2020-12-24 16:37
Gotcha. `ss -plnt | greo 8443` returns nothing.

I do see the service when I run `service --status-all | grep haproxy`

**Comment by domainicus** [comment] 2020-12-24 16:39
Could you follow the instructions at https://github.com/mitre/fieldmanual/blob/master/sphinx-docs/Plugin-library.md#ssl to set up SSL with a self-signed certificate? Then check to see if haproxy is listening?

**Comment by cyber-yinzer** [comment] 2020-12-24 16:48
I have my LetsEncrypt cert in the `conf` directory and ran through those steps. Should I run through the process of enabling the plugin again? Or go through the steps again with the self-signed cert?

**Comment by domainicus** [comment] 2020-12-24 16:53
Ideally, reinstall the plugin from git (removing changes to the haproxy.conf file made in the templates directory) and follow the instructions with a self-signed certificate. To remove the variable of the LetsEncrypt cert.

**Comment by cyber-yinzer** [comment] 2020-12-24 17:13
ok, in order...

1. Killed LetsEncrypt certificate
2. Killed haproxy.conf
3. Restore template to default setting
4. Removed haproxy
5. Rebooted
6. Installed haproxy
7. Rebooted
8. Followed steps 
9. Started Caldera
10. Enabled SSL + added port to app.contact.http
11. Stopped Caldera
12. Started Caldera
13. Can't access over 8443 but can on 8888

Ran `ss -plnt | grep 8443` and nothing returns.

Oddly enough, I ran this command right after I closed caldera and it returned my PID.

**Comment by domainicus** [comment] 2020-12-24 17:19
Is the plugin enabled? Can you see it in the sidebar if you access CALDERA on 8888?

**Comment by cyber-yinzer** [comment] 2020-12-24 17:24
It does not. I have to go back in and enable it again.

It flashes in the bottom bar that the "You enabled a new plugin! Bummer that it is not available until your next server restart."

I do not see it appear in the sidebar and when I stop/start the service, the "Enable plugin:" verbose does not show SSL as a loaded svc.

**Comment by domainicus** [comment] 2020-12-24 17:34
You'll have to add ssl to the plugins list when the server is stopped. Let me know if that works or if there are any error messages when the server restarts.

**Comment by cyber-yinzer** [comment] 2020-12-24 17:41
Plugin ran this time and I see the service listening:

` ss -plnt | grep 8443`
`LISTEN   0         2000                0.0.0.0:8443             0.0.0.0:*        users:(("haproxy",pid=2213,fd=6)) `

I switched app.contact.http to https://{myIP}:8443 and I can get to caldera on both 8888 & 8443.

Is this expected?

Also, will 8443 stay now or will I need to modify each startup?

**Comment by domainicus** [comment] 2020-12-24 17:44
The SSL service should stay. The 8888 service will stay too, since haproxy is forwarding traffic there. You can block access to this with your firewall, or by changing the CALDERA up to listen on 127.0.0.1 instead of 0.0.0.0.

Next, I'd try getting you LetsEncrypt cert set up in place of the self-signed cert. Let me know if there's any issues with that.

**Comment by cyber-yinzer** [comment] 2020-12-24 17:48
To clarify, in /caldera/conf/config.yml

Change `host:0.0.0.0` to `host:127.0.0.1` and I'll be able to use UFW or my perimeter FW to block 8888?

**Comment by domainicus** [comment] 2020-12-24 17:50
Making that change will have CALDERA listen only on the loopback interface instead of all interfaces. This won't be accessible to other hosts, so UFW won't be necessary.

The haproxy service will listen on all interfaces and route any requests to the CALDERA service on the loopback interface.

**Comment by cyber-yinzer** [comment] 2020-12-24 17:59
BOOM! 

Made the changes, flipped my LetsEncrypt back, and I'm on 8443 with the trusted cert.

**Comment by domainicus** [comment] 2020-12-24 18:05
Perfect, closing the issue. Assign me if you have any other issues.

If you have any edits to the instructions that might help others feel free to make a PR on https://github.com/mitre/fieldmanual

**Closed by domainicus** 2020-12-24 18:05 UTC
Labels: bug
