### ISSUE TITLE
don't see all abilities

### ISSUE THREAD

**Issue by Iwatch31** [mitre/caldera#574] opened 2019-10-09 14:11 UTC
Hi, 

Now that i recloned the latest release all my startup errors disappeared 
but when i go in gui, in abilitie function. I don't see all abilities but in my adversarie i saw the abilities in different phase. 

do yo know this bug ? 

thanks

**Comment by privateducky** [comment] 2019-10-09 20:36
I just did a re-clone to test this out but am not able to reproduce this.

What browser are you using? Have you made any changes to the code? Are there any errors in the JavaScript console of the browser?

**Comment by Iwatch31** [comment] 2019-10-10 07:21
i'm using chrome, I did not make a change in the code. 
In console of my web browser the only mistake are : 
```
Uncaught ReferenceError: None is not defined at HTMLSelectElement.onchange (VM75 gui:263)
onchange @ VM75 gui:263
```

**Comment by privateducky** [comment] 2019-10-11 10:55
we passed this around the team, no one is able to reproduce this. are you running the server on a linux, Mac or Windows? what version? can you clear your browser cache and see if the error goes away?

**Comment by privateducky** [comment] 2019-10-18 22:06
ah-- yes, that is a bug in the prior version. that is fixed in the master code and will be part of the next release.

**Closed by privateducky** 2019-10-18 22:06 UTC
