### ISSUE TITLE
Fieldmanual Link Broken

### ISSUE THREAD

**Issue by MrOrOneEquals1** [mitre/caldera#1883] opened 2020-09-23 01:31 UTC
The link to the Fieldmanual appears to be broken.  It looks like it should open a file /doc/index.html, but I can't find that file in the Caldera folders.

**Comment by unkempthenry** [comment] 2020-09-24 00:58
@MrOrOneEquals1 , I haven't been able to reproduce this. 

The documentation files should be getting built by caldera as it starts up.  If it runs into an error, then there will likely be some indication in the console output.  I haven't encountered it on fresh installs of 2.8.0 on an ubuntu VM, and I also haven't noticed it on a macbook do I do fair amount of work on. 

Could you check caldera's output and report back if you see anything telling in there?  Or, share some details about the system you're running it on? 

For example, here's what the output looks like when things go right: 

```
2020-09-23 17:50:59 - INFO  (hook.py:29 build_docs) b'Running Sphinx v3.0.4\nCreating file _generated/app.api.rst.\nCreating file _generated/app.api.packs.rst.\nCreating file _generated/app.contacts.rst.\nCreating file _generated/app.contacts.handles.rst.\nCreating file _generated/app.learning.rst.\nCreating file _generated/app.objects.rst.\nCreating file _generated/app.objects.interfaces.rst.\nCreating file _generated/app.objects.secondclass.rst.\nCreating file _generated/app.service.rst.\nCreating file _generated/app.service.interfaces.rst.\nCreating file _generated/app.utility.rst.\nCreating file _generated/modules.rst.\nloading pickled environment... done\nbuilding [mo]: targets for 0 po files that are out of date\nbuilding [html]: targets for 0 source files that are out of date\nupdating environment: 0 added, 1 changed, 0 removed\nreading sources... [100%] index\n\nlooking for now-outdated files... none found\npickling environment... done\nchecking consistency... done\npreparing documents... done\nwriting output... [100%] index\n\ngenerating indices...  genindex py-modindexdone\nwriting additional pages...  searchdone\ncopying static files... ... done\ncopying extra files... done\ndumping search index in English (code: en)... done\ndumping object inventory... done\nbuild succeeded, 3 warnings.\n\nThe HTML pages are in plugins/fieldmanual/sphinx-docs/_build/html.\n'
```

**Comment by wbooth** [comment] 2020-10-12 16:40
This issue should be addressed in this PR: https://github.com/mitre/fieldmanual/pull/20
If it persists or have further questions please re-open this ticket or open a new one!

**Closed by wbooth** 2020-10-12 16:40 UTC
Labels: bug
