### ISSUE TITLE
4.0.0-beta ImportError

### ISSUE THREAD

**Issue by dkorzhevin** [mitre/caldera#2526] opened 2022-03-21 15:46 UTC
Hello,

I've followed documentation and prepared docker with 4.0.0-beta, but having issues while trying to start:

`> docker run -p 7010:7010 -p 7011:7011/udp -p 7012:7012 -p 8888:8888 caldera:server
Traceback (most recent call last):
  File "server.py", line 8, in <module>
    import aiohttp_apispec
  File "/usr/local/lib/python3.8/dist-packages/aiohttp_apispec/__init__.py", line 1, in <module>
    from .aiohttp_apispec import AiohttpApiSpec, setup_aiohttp_apispec
  File "/usr/local/lib/python3.8/dist-packages/aiohttp_apispec/aiohttp_apispec.py", line 10, in <module>
    from jinja2 import Template
  File "/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.8/dist-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/dist-packages/markupsafe/__init__.py)`

**Comment by dkorzhevin** [comment] 2022-03-21 15:47
There was no errors with docker build:

`> docker build . -t caldera:server
[+] Building 2.3s (26/26) FINISHED
 => [internal] load build definition from Dockerfile                                                                                   0.0s
 => => transferring dockerfile: 37B                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                      0.0s
 => => transferring context: 35B                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/ubuntu:focal                                                                        2.1s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                          0.0s
 => [internal] load build context                                                                                                      0.1s
 => => transferring context: 85.17kB                                                                                                   0.1s
 => [ 1/20] FROM docker.io/library/ubuntu:focal@sha256:bea6d19168bbfd6af8d77c2cc3c572114eb5d113e6f422573c93cb605a0e2ffb                0.0s
 => CACHED [ 2/20] RUN ln -snf /usr/share/zoneinfo/UTC /etc/localtime &&     echo UTC > /etc/timezone                                  0.0s
 => CACHED [ 3/20] WORKDIR /usr/src/app                                                                                                0.0s
 => CACHED [ 4/20] RUN apt-get update &&     apt-get -y install python3 python3-pip golang git                                         0.0s
 => CACHED [ 5/20] RUN if [ "false" = "true" ] ; then apt-get -y install mingw-w64; fi                                                 0.0s
 => CACHED [ 6/20] ADD requirements.txt .                                                                                              0.0s
 => CACHED [ 7/20] RUN pip3 install --no-cache-dir -r requirements.txt                                                                 0.0s
 => CACHED [ 8/20] ADD . .                                                                                                             0.0s
 => CACHED [ 9/20] RUN go get github.com/grandcat/zeroconf                  github.com/google/go-github/github            github.com/  0.0s
 => CACHED [10/20] WORKDIR /usr/src/app/plugins/sandcat                                                                                0.0s
 => CACHED [11/20] RUN ./update-agents.sh                                                                                              0.0s
 => CACHED [12/20] RUN mkdir /tmp/gocatextensionstest                                                                                  0.0s
 => CACHED [13/20] RUN cp -R ./gocat-extensions /tmp/gocatextensionstest/gocat                                                         0.0s
 => CACHED [14/20] RUN cp -R ./gocat /tmp/gocatextensionstest/                                                                         0.0s
 => CACHED [15/20] RUN cp ./update-agents.sh /tmp/gocatextensionstest/update-agents.sh                                                 0.0s
 => CACHED [16/20] WORKDIR /tmp/gocatextensionstest                                                                                    0.0s
 => CACHED [17/20] RUN mkdir /tmp/gocatextensionstest/payloads                                                                         0.0s
 => CACHED [18/20] RUN ./update-agents.sh                                                                                              0.0s
 => CACHED [19/20] RUN if [ ! -d "/usr/src/app/plugins/atomic/data/atomic-red-team" ]; then       git clone --depth 1 https://github.  0.0s
 => CACHED [20/20] WORKDIR /usr/src/app                                                                                                0.0s
 => exporting to image                                                                                                                 0.0s
 => => exporting layers                                                                                                                0.0s
 => => writing image sha256:bfd9ea3bc420c7cd4f7236c1f1f79e1352df2cf8027d8c17c4a008b46dab6c11                                           0.0s
 => => naming to docker.io/library/caldera:server`

**Comment by clenk** [comment] 2022-03-21 17:06
This looks like a duplicate of https://github.com/mitre/caldera/issues/2496. Please try the solution posted there:
> `pip3 install markupsafe==2.0.1`, or by updating to the the current master of Caldera, where we've fixed the problem manually in our requirements.txt file.

**Closed** 2022-03-29 16:02 UTC
Labels: bug
