### ISSUE TITLE
ModuleNotFoundError: No module named 'plugins.manx.app'

### ISSUE THREAD

**Issue by D3ngX1n** [mitre/caldera#2176] opened 2021-06-10 03:35 UTC
python3 server.py
2021-06-10 11:34:41 - INFO  (server.py:112 <module>) Using main config from conf/local.yml
2021-06-10 11:34:42 - ERROR (app_svc.py:158 validate_requirement) go does not meet the minimum version of 1.11
Traceback (most recent call last):
  File "server.py", line 140, in <module>
    run_tasks(services=app_svc.get_services())
  File "server.py", line 54, in run_tasks
    loop.run_until_complete(app_svc.register_contacts())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/f/Nettools/caldera-master/app/service/app_svc.py", line 137, in register_contacts
    contact_class = import_module(contact_module_name).Contact
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/f/Nettools/caldera-master/app/contacts/contact_tcp.py", line 7, in <module>
    from plugins.manx.app.c_session import Session
ModuleNotFoundError: No module named 'plugins.manx.app'

**Comment by D3ngX1n** [comment] 2021-06-10 03:55
> Looks like your first issue -- we aim to respond to issues as quickly as possible. In the meantime, check out our documentation here: http://caldera.readthedocs.io/

thanks

**Comment by d4rkr41n** [comment] 2021-06-25 16:14
To add to this thread, it is possible that the problem is that the plugins/manx folder is empty. This can be fixed by recursively pulling the repo.

```git clone https://github.com/mitre/caldera.git --recursive --branch 3.1.0
cd caldera
pip3 install -r requirements.txt
python3 server.py --insecure```

**Comment by blackwidow0616** [comment] 2021-06-29 20:27
I agree with @d4rkr41n that this is likely due to the manx folder being empty. Another fix for this would be to clone just the manx repo. From `caldera/plugins`, you can run `git clone https://github.com/mitre/manx.git` to just grab the manx repo.

Also it might be worthwhile to double check your `conf/local.yml` to make sure manx is enabled or disabled as you wish.

**Comment by blackwidow0616** [comment] 2021-07-06 20:21
Hopefully this resolves your issue. If you’re still having any problems, please feel free to re-open or start a new ticket. Thanks!

**Closed by blackwidow0616** 2021-07-06 20:21 UTC
Labels: bug
