### ISSUE TITLE
training plugin error

### ISSUE THREAD

**Issue by DG9Jww** [mitre/caldera#2681] opened 2022-10-26 01:55 UTC
**Describe the bug**
2022-10-26 09:01:26 - INFO  (app_svc.py:116 load) Enabled plugin: access
2022-10-26 09:01:26 - INFO  (app_svc.py:116 load) Enabled plugin: atomic
2022-10-26 09:01:26 - INFO  (app_svc.py:116 load) Enabled plugin: compass
2022-10-26 09:01:26 - INFO  (app_svc.py:116 load) Enabled plugin: debrief
2022-10-26 09:01:26 - INFO  (app_svc.py:116 load) Enabled plugin: fieldmanual
2022-10-26 09:01:26 - INFO  (app_svc.py:116 load) Enabled plugin: manx
2022-10-26 09:01:26 - INFO  (app_svc.py:116 load) Enabled plugin: response
2022-10-26 09:06:26 - INFO  (app_svc.py:116 load) Enabled plugin: sandcat
2022-10-26 09:06:26 - INFO  (app_svc.py:116 load) Enabled plugin: stockpile
2022-10-26 09:06:26 - ERROR (c_plugin.py:91 _load_module) Error importing plugin=training, 'EntryPoints' object has no attribute 'get'
2022-10-26 09:06:26 - ERROR (c_plugin.py:59 load_plugin) Error loading plugin=training, 'NoneType' object has no attribute 'description'
2022-10-26 09:06:26 - ERROR (c_plugin.py:91 _load_module) Error importing plugin=training, 'EntryPoints' object has no attribute 'get'
2022-10-26 09:06:26 - ERROR (c_plugin.py:70 enable) Error enabling plugin=training, 'NoneType' object has no attribute 'enable'
2022-10-26 09:06:26 - INFO  (app_svc.py:116 load) Enabled plugin: training
2022-10-26 09:06:26 - INFO  (logging.py:92 log) Creating SSH listener on 0.0.0.0, port 8022
2022-10-26 09:06:26 - INFO  (server.py:741 start) serving on 0.0.0.0:2222

**To Reproduce**
When I started the server,the error appeared.

**Expected behavior**
load  plugin successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/84201009/197916152-7291f7e6-60c5-4393-a156-dd73c9878d5b.png)

**Desktop (please complete the following information):**
 - OS: Centos7
 - Browser Chrome
 - Version 4.1.0
 - Python 3.7.9

**Comment by elegantmoose** [comment] 2022-11-21 16:41
@DG9Jww  Still having issues? Can you try re-pulling Training plugin?

**Comment by mbielejeski** [comment] 2022-12-09 23:42
I am not the original poster but I ran into the same issue today.  I added some additional logging to print out the stack trace of the exception to find out where it was coming from.

```
2022-12-09 23:18:20 - ERROR (c_plugin.py:92 _load_module) 'EntryPoints' object has no attribute 'get'
Traceback (most recent call last):
  File "/srv/git/caldera/app/objects/c_plugin.py", line 89, in _load_module
    return import_module('plugins.%s.hook' % self.name)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/git/caldera/plugins/training/__init__.py", line 4, in <module>
    from plugins.training.app.c_flag import Flag
  File "/srv/git/caldera/plugins/training/app/c_flag.py", line 5, in <module>
    import markdown
  File "/srv/git/caldera/pyenv/lib64/python3.7/site-packages/markdown/__init__.py", line 29, in <module>
    from .core import Markdown, markdown, markdownFromFile  # noqa: E402
  File "/srv/git/caldera/pyenv/lib64/python3.7/site-packages/markdown/core.py", line 26, in <module>
    from . import util
  File "/srv/git/caldera/pyenv/lib64/python3.7/site-packages/markdown/util.py", line 87, in <module>
    INSTALLED_EXTENSIONS = metadata.entry_points().get('markdown.extensions', ())
```

I was able to fix the issue by updating requirements.txt to reference a newer version of the Markdown package.
I changed the line `Markdown==3.3.3` to `Markdown==3.3.5`.

**Comment by elegantmoose** [comment] 2022-12-20 13:50
@mbielejeski Thats very odd. Im not able to reproduce the error and markdown 3.3.3 works fine.

Closing but @DG9Jww if still having issues please reopen.

**Closed by elegantmoose** 2022-12-20 13:50 UTC
Labels: bug

**Comment by jim-wojno** [comment] 2023-06-21 19:21
I'm getting the exact same error - brand new install pulling the full caldera repo - running on CentOS 8.5.2111.

**Comment by jim-wojno** [comment] 2023-06-21 19:22
2023-06-21 15:19:10 - INFO  (logging.py:92 log) Creating SSH listener on 0.0.0.0, port 8022
2023-06-21 15:19:10 - INFO  (app_svc.py:116 load) Enabled plugin: access
2023-06-21 15:19:23 - INFO  (app_svc.py:116 load) Enabled plugin: atomic
2023-06-21 15:19:23 - INFO  (app_svc.py:116 load) Enabled plugin: compass
2023-06-21 15:19:24 - INFO  (app_svc.py:116 load) Enabled plugin: debrief
2023-06-21 15:19:24 - INFO  (app_svc.py:116 load) Enabled plugin: fieldmanual
2023-06-21 15:19:24 - INFO  (app_svc.py:116 load) Enabled plugin: manx
2023-06-21 15:19:24 - INFO  (app_svc.py:116 load) Enabled plugin: response
2023-06-21 15:19:31 - INFO  (app_svc.py:116 load) Enabled plugin: sandcat
2023-06-21 15:19:31 - INFO  (app_svc.py:116 load) Enabled plugin: stockpile
2023-06-21 15:19:31 - ERROR (c_plugin.py:91 _load_module) Error importing plugin=training, 'EntryPoints' object has no attribute 'get'
2023-06-21 15:19:31 - ERROR (c_plugin.py:59 load_plugin) Error loading plugin=training, 'NoneType' object has no attribute 'description'
2023-06-21 15:19:31 - ERROR (c_plugin.py:91 _load_module) Error importing plugin=training, 'EntryPoints' object has no attribute 'get'
2023-06-21 15:19:31 - ERROR (c_plugin.py:70 enable) Error enabling plugin=training, 'NoneType' object has no attribute 'enable'
2023-06-21 15:19:31 - INFO  (app_svc.py:116 load) Enabled plugin: training
2023-06-21 15:19:31 - INFO  (server.py:741 start) serving on 0.0.0.0:2222

**Comment by jim-wojno** [comment] 2023-06-21 22:06
The following command appeared to resolve the issue:

cd caldera
!pip install importlib-metadata==4.13.0

The run caldera as normal:
python3 server.py --insecure
