### ISSUE TITLE
Variable not filled with fact

### ISSUE THREAD

**Issue by perra22** [mitre/caldera#843] opened 2019-11-28 11:13 UTC
Hi, i've created a new ability that implement [T1087](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1087/T1087.md#atomic-test-1---enumerate-all-accounts) with a variable called #{host.user.accounts} that represent the path to the file where redirect the output of the command:

```
---
- id: 1fb7710e-d0e6-4cef-b760-9cff3dcfdc56
  name: Enumerate all accounts
  description: Enumerate all accounts by copying /etc/passwd to another file
  tactic: discovery
  technique:
    attack_id: T1087
    name: Account Discovery
  platforms:
    linux:
      sh:
        command: cat /etc/passwd > #{host.user.accounts}
```
then i've created the fact:
```
---
id: 7fd73387-7165-4599-9332-0684c35c168e
name: first-op
facts:
  - trait: remote.host.ip
    value: 0.0.0.0
  - trait: host.user.accounts
    value: /home/ubuntu/stage/exfil/accounts.txt
```
so i expected that the variable would have been replaced with the value when i start an operation with this ability but it isn't. The output is:

> sh: 1: Syntax error: end of file unexpected

If i set the path hard coded in the ability it works. 
Thanks for the help!

**Comment by khyberspache** [comment] 2019-12-02 17:05
You've stumbled upon what is called "scoping variables."  In order to prune down facts (i.e. only use files discovered on a machine on that specific machine), we block the planner from using variables that begin with `host` from being used unless they are "learned" from that host.  So hard coded facts wouldn't work and that is an intentional design strategy.

If you change the variable to `#{file.user.accounts}` the fact will get rendered properly.
@wbooth implemented a lot of the scoping variable work, so he can offer more suggestions.

**Comment by perra22** [comment] 2019-12-02 19:48
Thank you for the answer!

**Comment by perra22** [comment] 2019-12-03 08:43
I've tried to change the fact and variable name to #{file.user.accounts} but it isn't rendered properly.

![Capture](https://user-images.githubusercontent.com/18696951/70034171-0c6baf80-15b1-11ea-80c6-9f2c7e76bd5e.PNG)

![Capture3](https://user-images.githubusercontent.com/18696951/70034350-4fc61e00-15b1-11ea-8941-05cf73662d69.PNG)

![Capture1](https://user-images.githubusercontent.com/18696951/70034174-0d044600-15b1-11ea-8b80-c296277f35f4.PNG)

![Capture2](https://user-images.githubusercontent.com/18696951/70034176-0d044600-15b1-11ea-86a2-5b015fcbdbd0.PNG)

**Comment by wbooth** [comment] 2019-12-03 09:47
Thanks for all the screen shots, can you post the fact source as well?

**Comment by perra22** [comment] 2019-12-03 09:52
This is the fact source code:
```
---

id: 7fd73387-7165-4599-9332-0684c35c168e
name: first-op
facts:
  - trait: remote.host.ip
    value: 0.0.0.0
  - trait: file.user.accounts
    value: /home/ubuntu/stage/exfil/accounts.txt

```
and this is the screenshot of the sources:

![Capture4](https://user-images.githubusercontent.com/18696951/70039796-cb789880-15ba-11ea-8855-14c834b50916.PNG)

**Comment by khyberspache** [comment] 2019-12-03 23:08
Did you select the `first-op` fact group when you started the operation? can you post what your operation config looks like before you run it?  Then can you provide the operation JSON download after the operation runs?  Thanks.

**Comment by perra22** [comment] 2019-12-04 08:36
Yes, i've selected `first-op` as fact group.
This is the operation config:
```
id: 46cbce05-420c-4ee7-b7a1-956a2225ed65
name: First Attack 1.2
description: Prima implementazione di un processo di attacco
phases:
  1:
  - 85341c8c-4ecb-4579-8f53-43e3e91d7617
  - 1fb7710e-d0e6-4cef-b760-9cff3dcfdc56
```
and this is the report:

[operation_report_rookie#41219.zip](https://github.com/mitre/caldera/files/3920871/operation_report_rookie.41219.zip)

**Comment by privateducky** [comment] 2019-12-06 17:54
ok-- when I went to reproduce this, I noticed a bug when starting an operation with a new adversary - if the page hadn't been refreshed since the adversary was created. 

I fixed this, along with a handful of other wonky JavaScript areas. Can you retry this on a fresh clone of CALDERA and see if that works? 

If not, I'll try this out on a Linux VM (original testing for me is on MacOS).

**Comment by perra22** [comment] 2019-12-09 11:01
Hi, 
I've created a new fresh clone to see if the fix works but when I open Caldera home page from Chrome it looks like the screenshot:

![Capture](https://user-images.githubusercontent.com/18696951/70430507-40484880-1a7b-11ea-9cdd-0aefa42b0866.PNG)

**Comment by privateducky** [comment] 2019-12-09 11:09
Try clearing your browser cache

**Comment by perra22** [comment] 2019-12-09 11:18
Now when I create a new Adversary (with the ability to test) there is an error:

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<DataService._load_abilities() done, defined at /home/ubuntu/stage/caldera_master/caldera/app/service/data_svc.py:181> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/home/ubuntu/stage/caldera_master/caldera/app/service/data_svc.py", line 183, in _load_abilities
  File "/home/ubuntu/stage/caldera_master/caldera/app/utility/base_world.py", line 36, in strip_yml
OSError: [Errno 24] Too many open files: 'plugins/stockpile/data/abilities/discovery/5f77ecf9-613f-4863-8d2f-ed6b447a4633.yml'
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 154, in factory
  File "/home/ubuntu/stage/caldera_master/caldera/plugins/stockpile/app/http.py", line 30, in _instructions
  File "/home/ubuntu/stage/caldera_master/caldera/app/service/contact_svc.py", line 40, in handle_heartbeat
  File "/home/ubuntu/stage/caldera_master/caldera/app/objects/c_agent.py", line 27, in __init__
  File "/home/ubuntu/stage/caldera_master/caldera/app/utility/base_object.py", line 8, in __init__
  File "/home/ubuntu/stage/caldera_master/caldera/app/utility/logger.py", line 9, in __init__
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
OSError: [Errno 24] Too many open files: '/home/ubuntu/stage/caldera_master/caldera/logs/object.log'
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
_/Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/contact.API.GetInstructions(0xc000078c30, 0x93c260)
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/contact/api.go:48 +0x524
main.runAgent(0x757560, 0x954a40, 0xc000078c30)
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/sandcat.go:36 +0x441
main.main()
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/sandcat.go:124 +0x78f
```

**Comment by privateducky** [comment] 2019-12-09 11:35
Ah yes, that’s an operating system error- try increasing your open file limit by running “unlimit -n 10000” on your server and restart caldera

**Comment by privateducky** [comment] 2019-12-09 11:36
Command is: ulimit-n 10000

**Comment by perra22** [comment] 2019-12-09 13:22
Ok thanks. The Error has changed in:

```
DEBUG:app_svc:Starting operation: rookie#4
DEBUG:planning_svc:Generated 1 links for 2322
Traceback (most recent call last):
  File "/home/ubuntu/stage/caldera_master/caldera/app/service/app_svc.py", line 94, in run_operation
    await planner.execute(phase)
  File "/home/ubuntu/stage/caldera_master/caldera/plugins/stockpile/app/sequential.py", line 8, in execute
    for link in await self.planning_svc.get_links(operation=self.operation, phase=phase):
  File "/home/ubuntu/stage/caldera_master/caldera/app/service/planning_svc.py", line 30, in get_links
    links.extend(await self._generate_and_trim_links(agent, operation, abilities, link_status, trim))
  File "/home/ubuntu/stage/caldera_master/caldera/app/service/planning_svc.py", line 72, in _generate_and_trim_links
    agent_links = await self.trim_links(operation, agent_links, agent)
  File "/home/ubuntu/stage/caldera_master/caldera/app/utility/base_planning_svc.py", line 23, in trim_links
    links[:] = await self.add_test_variants(links, agent, operation)
  File "/home/ubuntu/stage/caldera_master/caldera/app/utility/base_planning_svc.py", line 48, in add_test_variants
    copy_link = copy.deepcopy(link)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects

```

when i start the operation. The adversary includes only the ability 
`c7ec57cd-933e-42b6-99a4-e852a9e57a33` (Account discovery (All))

**Comment by perra22** [comment] 2019-12-11 09:50
I've seen that @wbooth has created a pull request (#850) for this type of error, when it will be accepted?

**Comment by perra22** [comment] 2019-12-11 09:58
I noticed that the error happens only when i use abilities with variables.
Thanks for the support!

**Comment by privateducky** [comment] 2019-12-12 11:04
@wbooth's PR is just a shortcut -- it won't stop the issue, it'll just hide the error. 

we've seen this stack trace occasionally, which I think may be a specific python version issue around the 'copy' command.

we'll look at this more closely today.

**Comment by privateducky** [comment] 2019-12-12 11:34
ok I took a quick look at this. 

**the problem:** when python does the deep copy command, to create a "link" (a variation of a command based on variables) it pickles the object during the copy - which fails due to a non-python object being stored inside the copied link. this only seems to occur on specific abilities and on specific installations of python on linux.

**the solution**: I'm having trouble reproducing this quickly, so I could use your help. I just merged in a quick patch which will swallow/skip over this exception - and also log the full object that is failing to pickle. 

can you re-run your operation and pass me back what prints out in your logs/console?

**Comment by perra22** [comment] 2019-12-12 13:22
Hi,
i've done a git pull and now when i start sandcat i got this error:

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/stage/caldera_master/caldera/app/service/file_svc.py", line 28, in download
    payload, display_name = await self.special_payloads[payload](request.headers)
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_response.py", line 567, in body
    self._body = body = payload.PAYLOAD_REGISTRY.get(body)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/payload.py", line 106, in get
    raise LookupError()
aiohttp.payload.LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 154, in factory
    response = await handler(request)
  File "/home/ubuntu/stage/caldera_master/caldera/app/service/file_svc.py", line 35, in download
    return web.HTTPNotFound(body=e)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_exceptions.py", line 96, in __init__
    body=body, text=text, content_type=content_type)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_response.py", line 545, in __init__
    self.body = body
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_response.py", line 569, in body
    raise ValueError('Unsupported body type %r' % type(body))
ValueError: Unsupported body type <class 'ValueError'>
/tmp/sandcat-linux: line 1: 500: command not found
/tmp/sandcat-linux: line 3: Server: command not found

```
so i can't reproduce the "deepcopy" error.

**Comment by privateducky** [comment] 2019-12-12 14:05
we just did a merge to a few plugins this morning -- either fresh clone or do a git pull on each plugin. then retry

**Comment by perra22** [comment] 2019-12-12 14:16
I've done a fresh clone and reproduced the error:

```
DEBUG:app_svc:Starting operation: rookie
DEBUG:planning_svc:Generated 1 links for 430322
Could not create test variant: can't pickle _thread.RLock objects
{'log': <app.utility.logger.Logger object at 0x7f4ef4fea9e8>, 'id': None, 'command': 'Y2F0IC9ldGMvcGFzc3dkID4gI3tmaWxlLmhvc3QuYWNjb3VudHN9', 'operation': 803296, 'paw': '430322', 'cleanup': 0, 'ability': <app.objects.c_ability.Ability object at 0x7f4ef4feac88>, 'status': -3, 'score': 0, 'jitter': 8, 'decide': datetime.datetime(2019, 12, 12, 14, 15, 27, 968546), 'pid': None, 'collect': None, 'finish': None, 'facts': [], 'relationships': [], 'used': []}
DEBUG:data_svc:Loading data from: data
DEBUG:data_svc:Loading data from: plugins/stockpile/data
DEBUG:app_svc:Completed operation: rookie
 
```

**Comment by privateducky** [comment] 2019-12-12 14:25
ok lemme check

**Comment by privateducky** [comment] 2019-12-12 14:31
good stuff-- the issue is in either the log or ability object. I pushed up 1 more set of logs to capture these. can you re-pull the code (just the core caldera code is fine) and re-run it?

**Comment by perra22** [comment] 2019-12-12 14:35
The new log:

```
DEBUG:app_svc:Starting operation: rookie
DEBUG:planning_svc:Generated 1 links for 670656
Could not create test variant: can't pickle _thread.RLock objects
{'log': None, 'id': None, 'command': 'Y2F0IC9ldGMvcGFzc3dkID4gI3tmaWxlLmhvc3QuYWNjb3VudHN9', 'operation': 397713, 'paw': '670656', 'cleanup': 0, 'ability': <app.objects.c_ability.Ability object at 0x7fc99d209358>, 'status': -3, 'score': 0, 'jitter': 6, 'decide': datetime.datetime(2019, 12, 12, 14, 34, 33, 503583), 'pid': None, 'collect': None, 'finish': None, 'facts': [], 'relationships': [], 'used': []}
{'log': <app.utility.logger.Logger object at 0x7fc99d209b70>, 'ability_id': 'c7ec57cd-933e-42b6-99a4-e852a9e57a33', 'tactic': 'discovery', 'technique_name': 'Account Discovery', 'technique_id': 'T1087', 'name': 'Account Discovery (all)', 'test': 'Y2F0IC9ldGMvcGFzc3dkID4gI3tmaWxlLmhvc3QuYWNjb3VudHN9', 'description': 'The net utility is executed via cmd to enumerate domain user accounts.', 'cleanup': None, 'executor': 'sh', 'platform': 'linux', 'payload': None, 'parsers': [], 'requirements': [], 'privilege': None}
DEBUG:data_svc:Loading data from: plugins/stockpile/data
DEBUG:data_svc:Loading data from: data
DEBUG:app_svc:Completed operation: rookie
```

**Comment by privateducky** [comment] 2019-12-12 14:42
perfect. ok I think it must be the logger object. the ability has a logger on it as well-- I just merged another patch in to remove that. can you re-run one more time?

**Comment by perra22** [comment] 2019-12-12 14:49
I've re-run the operation and now it works! Thank you very much for the support.

**Comment by privateducky** [comment] 2019-12-12 14:54
great! thanks for your help debugging!

**Comment by privateducky** [comment] 2019-12-12 16:29
ok I just merged in the "final fix" and removed the ad-hoc patch. Let me know if you see any issues, otherwise I'll close this off for now. thanks again for bringing this to our attention!

**Closed by privateducky** 2019-12-12 16:29 UTC
