### ISSUE TITLE
Unable to clone repo

### ISSUE THREAD

**Issue by wronglebowsk** [mitre/caldera#1210] opened 2020-02-12 17:00 UTC
I keep getting issues trying to clone the repo given the instructions on the front page. 

`git clone https://github.com/mitre/caldera.git --recursive --branch x.x.x `

For example I run 

`git clone https://github.com/mitre/caldera.git --recursive --branch 2.5.1`

I keep getting an error 

`Fetched in submodule path 'plugins/sandcat', but it did not contain e5aef68649178419b64e7d0d9cf4145e437df9ce. Direct fetching of that commit failed`

Is there a recommended workaround?

**Comment by khyberspache** [comment] 2020-02-12 17:51
I did some git history pruning (removed large files that were making the plugins large) yesterday and it looks like it messed up the commit hashes for the release.  Good find - I'll push a fix shortly

**Comment by khyberspache** [comment] 2020-02-12 18:46
@wronglebowsk I think it is fixed, you should be able to clone with 
`git clone https://github.com/mitre/caldera.git --recursive --branch 2.5.1`

Let me know.

**Comment by acyberhu60** [comment] 2020-02-18 16:47
The issue is apparently persisting for all releases prior to 2.5.1.  I tried for the 2.3.2, 2.4.0 and 2.5.0 tagged releases.

command:
`git clone https://github.com/mitre/caldera.git --recursive --branch 2.3.2`
output error:
 `Fetched in submodule path 'plugins/sandcat', but it did not contain 33f0af6ae3056cdfd1a921f3f355941a42709ea3. Direct fetching of that commit failed` 

command:
`git clone https://github.com/mitre/caldera.git --recursive --branch 2.4.0`
output error:
 `Fetched in submodule path 'plugins/sandcat', but it did not contain 6d7009d6bb0eba5f2722984805e7bc45e3c768ea. Direct fetching of that commit failed.` 

command:
`git clone https://github.com/mitre/caldera.git --recursive --branch 2.5.0`
output error:
 `Fetched in submodule path 'plugins/sandcat', but it did not contain e5aef68649178419b64e7d0d9cf4145e437df9ce. Direct fetching of that commit failed.`

**Comment by 0xThiebaut** [comment] 2020-02-18 19:14
> I did some git history pruning (removed large files that were making the plugins large) yesterday and it looks like it messed up the commit hashes for the release. Good find - I'll push a fix shortly

This is something that should **NEVER** happen. We relied on a specific Caldera version for demos in a class which we did properly by using version pinning. This broke the deployment while the class was using it resulting in us having to rewrite the Caldera part on-the-fly. This is not how semantic versioning works.

**Comment by privateducky** [comment] 2020-02-18 21:13
@0xThiebaut agreed-- our attempt obviously failed-- we were hoping to prune the larger files from between the release tags but it unfortunately impacted all but the latest version of code. it was a tricky attempt to remove the ~500MB size of the full history of the repo. 

lesson learned on this though, as we see where we went wrong. we're working to verify and fix any broken releases that were impacted by this.

**Comment by 0xThiebaut** [comment] 2020-02-18 21:20
@privateducky I know this is still all under heavy development (and I appreciate it 😉), but might I suggest the usage of a dev branch in order to never touch the master in the future using `-f`?

**Comment by privateducky** [comment] 2020-02-18 21:32
thanks. we would have actually hit this on the development "git flow" as well. the main issue is each release has been slower than the last to clone, as every time we commit a larger binary file (make updates to an agent, for example), the history of the file is saved as well. so all of the sudden a tagged release may have 100+ versions of a large file. 

we were aiming to retroactively prune the releases to go clone quicker across the board, so we would have still tried this against the tagged releases, targeting their history to slim them down to their depth=1.

unfortunately, that kicked us in the butt. the good part of it though-- we learned how to do it, which takes some interesting GIT knowledge that we didn't know before. one thing i think we're still lacking are automated tests, in general, but specifically around validating our release versions.

**Comment by privateducky** [comment] 2020-02-18 21:34
on the topic of releases-- just today we cut 2.6.0! if you get a chance to toy with this, let me know. we'll be expanding on some of the concepts of autonomous incident response in future releases.

**Comment by 0xThiebaut** [comment] 2020-02-18 21:39
Sadly our class is running since Monday until Friday after which we plan on bundling caldera in a docker image to avoid such breaking changes in production. We have been patching systems to use 2.5.1 the entire day so we won't upgrade that today as we are looking to fix all our labs by tomorrow.

I might however contact you as I'm having trouble creating a regex parser on 2.5.1, lots of our labs relied on the regex feature from older releases.

**Comment by khyberspache** [comment] 2020-02-18 22:22
@0xThiebaut Which version did you need? I am going through and patching old releases right now.  I'll prioritize whichever one you need

**Comment by khyberspache** [comment] 2020-02-19 03:04
@acyberhu60 @0xThiebaut 2.5.0 patched.

**Comment by khyberspache** [comment] 2020-02-19 03:28
2.4.0 patched.

**Comment by 0xThiebaut** [comment] 2020-02-19 05:21
Hi,
Sorry for the delay, Brussels time zone 😉 
We relied on the even older 2.3.2

**Comment by acyberhu60** [comment] 2020-02-19 07:40
Would be great indeed if 2.3.2 were fixed, I've got some plugins that broke with the changes to the webgui introduced with version 2.4.0.

**Comment by khyberspache** [comment] 2020-02-19 14:15
I'll patch 2.3.2 and 2.2.0 right now

**Comment by khyberspache** [comment] 2020-02-19 14:38
@acyberhu60 @acyberhu60 2.3.2 patched.

**Comment by khyberspache** [comment] 2020-02-20 00:54
@acyberhu60 I'm closing this - if you have issues, just open a new ticket and we can address it.

**Closed by khyberspache** 2020-02-20 00:54 UTC
Labels: bug
