### ISSUE TITLE
launching server.py crashes because of deprecated  import

### ISSUE THREAD

**Issue by cventour** [mitre/caldera#2572] opened 2022-05-10 08:34 UTC
The markupsafe project has deprecated the soft_unicode function causing new caldera installations with latest pip requirements to crash if markupsafe 2.1.0 or above is installed. 

Error when launching. 

Traceback (most recent call last):
  File "/Users/cventour/caldera3/caldera/server.py", line 7, in <module>
    import aiohttp_apispec
  File "/usr/local/lib/python3.9/site-packages/aiohttp_apispec/__init__.py", line 1, in <module>
    from .aiohttp_apispec import AiohttpApiSpec, setup_aiohttp_apispec
  File "/usr/local/lib/python3.9/site-packages/aiohttp_apispec/aiohttp_apispec.py", line 10, in <module>
    from jinja2 import Template
  File "/usr/local/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.9/site-packages/markupsafe/__init__.py)

To support markupsafe , caldera needs to use soft_str instead of soft_unicode.

**Comment by yee-jonathan** [comment] 2022-05-12 09:16
This bug appears to be a duplicate of [#2496](https://github.com/mitre/caldera/issues/2496). MarkupSafe 2.0.1 seems to have been removed in [commit 2c990da01db3613c0799e3f98de427d1b691e88c](https://github.com/mitre/caldera/commit/2c990da01db3613c0799e3f98de427d1b691e88c)

**Comment by elegantmoose** [comment] 2022-05-23 21:30
@cventour - reopen if issue not fixed via other solutions proposed on #2496

**Closed by elegantmoose** 2022-05-23 21:30 UTC
