### ISSUE TITLE
Bug in rest_svc.py

### ISSUE THREAD

**Issue by triciah73** [mitre/caldera#1584] opened 2020-04-27 17:49 UTC
I believe line 221 in `update_operation`
```python
operation = await self.get_service('data_svc').locate('operations', match=dict(id=op_id))
```
should be
```python
operation = await self.get_service('data_svc').locate('operations', match=dict(id=int(op_id)))
```

This matches line 116 in `display_operation_report`. Without the change I get 

```bash
2020-04-27 11:09:41 - ERROR (rest_svc.py:221 validate) <HTTPNotFound Not Found not prepared>
2020-04-27 11:09:41 - ERROR (rest_api.py:100 rest_core) IndexError('list index out of range',)
Traceback (most recent call last):
  File "/home/analysis/Documents/caldera-2.6.6/app/api/rest_api.py", line 98, in rest_core
    return web.json_response(await options[request.method][index](data))
  File "/home/analysis/Documents/caldera-2.6.6/app/service/rest_svc.py", line 226, in update_operation
    operation[0].state = state
IndexError: list index out of range
```
With the change I still get 
```bash
2020-04-27 11:16:38 - ERROR (rest_svc.py:221 validate) <HTTPBadRequest Bad Request not prepared>
```
but I haven't found that issue yet.

**Comment by khyberspache** [comment] 2020-04-27 19:59
Can you provide steps to reproduce?

**Comment by triciah73** [comment] 2020-04-27 20:48
This throws errors in the server output, but returns data (attached):
```bash
curl -X PUT -H "KEY:$KEY" http://127.0.0.1:8888/api/rest -d '{"index":"operations","name":"testoperation5","adversary_id":"de07f52d-9928-4071-9142-cb1d3bd851e8"}' > operation.json
```
This seems to work fine (attached):
```bash
curl -X POST -H "KEY:$KEY" http://127.0.0.1:8888/api/rest -d '{"index":"operation_report","op_id":"446213"}' > operation_update.json
```
This is the issue described above:
```bash
curl -X POST -H "KEY:$KEY" http://127.0.0.1:8888/api/rest -d '{"index":"operation","op_id":"446213","state":"FINISHED"}' > update.json
```
With the fix described above this returns null instead of the `500 Internal Server Error` in update.txt below.

All of this is with 2.6.6 release

[operation.txt](https://github.com/mitre/caldera/files/4541909/operation.txt)
[operation_update.txt](https://github.com/mitre/caldera/files/4541910/operation_update.txt)
[update.txt](https://github.com/mitre/caldera/files/4541912/update.txt)

**Comment by triciah73** [comment] 2020-04-27 22:58
A couple of notes:

- I made a fresh clone of the repo and tried again and don't have any errors with step 1 above.
- when I use "finished" instead of "FINISHED" in step 3 I don't get any errors there either and it finishes the operation as expected (when also using the fix described above in rest_svc.py)

**Comment by khyberspache** [comment] 2020-04-27 23:48
@triciah73 thanks for the details. I've found the root cause. I actually want to rewrite that section of the code to better handle API fail scenarios.

**Comment by khyberspache** [comment] 2020-04-27 23:48
@privateducky

**Comment by triciah73** [comment] 2020-04-28 03:02
Was your root cause more general than the one I described? I found another bug in the same file where the operations weren't being deleted from the data store. This is evident if you run 

```bash
curl -X DELETE -H "KEY:$KEY" http://127.0.0.1:8888/api/rest -d '{"index":"operations","id":"420603"}'
```
then run 
```bash
curl -X POST -H "KEY:$KEY" http://127.0.0.1:8888/api/rest -d '{"index":"operation_report","op_id":"420603"}' > operation_update3.json
```
It will delete all the files in data/facts and data/results, but you still get all the information back if you request the report.

It looks like the culprit is line 104:
```python
await self.get_service('data_svc').remove('operations', data)
```

I think it should be (there may be a more elegant option):
```python
await self.get_service('data_svc').remove('operations', match=dict(id=int(data.get('id'))))
```
if you run the commands above with this fix then the second command will return a 500 error, which is what we would expect. I also added some debug messages on the `remove` function of `data_svc.py` to confirm that the operation was previously still in the `ram` dictionary and with the fix that it is being removed.

data_svc.py
```python
 async def remove(self, object_name, match):
        """
        Remove any c_objects which match a search

        :param object_name:
        :param match: dict()
        :return:
        """
        try:
            self.log.debug([obj.id for obj in self.ram[object_name]])
            self.ram[object_name][:] = [obj for obj in self.ram[object_name] if not obj.match(match)]
            self.log.debug([obj.id for obj in self.ram[object_name]])
        except Exception as e:
            self.log.error('[!] REMOVE: %s' % e)
```

server output before:
```bash
2020-04-27 19:33:34 - DEBUG (data_svc.py:132 remove) [715990, 420603, 660698]
2020-04-27 19:33:34 - DEBUG (data_svc.py:134 remove) [715990, 420603, 660698]
```

after fix:
```bash
2020-04-27 19:38:00 - DEBUG (data_svc.py:132 remove) [715990, 420603, 660698]
2020-04-27 19:38:00 - DEBUG (data_svc.py:134 remove) [715990, 660698]
```

If there's a more general fix that solves both of these issues please let me know!

**Comment by privateducky** [comment] 2020-04-28 12:36
ok, it looks like this is related to type inconsistencies in the REST API, in string/int representations of operation_id and state. we'll evaluate this in a future version (i.e., converting all to the same type) but in the meantime, I think solving through adding more documentation is the right move. 

I went ahead and updated our documentation page related to this, including an example of how to change state via the REST API: https://github.com/mitre/caldera/pull/1587

Let me know if there are any other areas in the REST API I can document while I'm in there. Hint: our front-end (GUI) is built on top of our REST API, so locating an example of how the REST API works generally means looking at what is calling the restRequest function in shared.js.

**Comment by privateducky** [comment] 2020-04-28 12:36
https://caldera.readthedocs.io/en/latest/The-REST-API.html

**Comment by triciah73** [comment] 2020-04-28 17:06
Thanks! That helps with troubleshooting. I think in the docs that `id` should be an int for the operation delete call.

Is there a way to make the operations started/created with the REST API show up in the GUI?

**Comment by triciah73** [comment] 2020-04-28 19:39
I tracked down the GUI "issue"...when you use the API key the permissions include red and blue (blue is in the list twice?). The logic in `_build_operation_object` says if the permissions include blue then the access is blue, otherwise it's red. This means all the API calls are defaulting to blue (and show up under blue in the GUI)

**Comment by privateducky** [comment] 2020-05-18 11:31
I'm updating the docs on the 'delete operation' to reflect the need for operation_id to be an integer.

**Comment by privateducky** [comment] 2020-05-18 11:39
secondarily, I kicked off a RED operation using the red key (ADMIN123) and it showed up fine under the operation GUI (for red):
```
curl -X PUT -H "KEY:ADMIN123" http://127.0.0.1:8888/api/rest -d '{"index":"operations","name":"testoperation1"}'
```

I did the same thing with the blue key (BLUEADMIN123) and it showed up only under the blue GUI page. I'm doing this against latest master code-- are you doing this against a release version or latest master?

**Comment by privateducky** [comment] 2020-05-18 11:42
actually, this remaining issue is a duplicate of: https://github.com/mitre/caldera/issues/1599

**Closed by privateducky** 2020-05-18 11:42 UTC
Labels: bug
